version: '3.7'
services:
  # React
  react:
    build:
      context: ./react/
    ports:
      - "3000:3000"
    volumes:
      - ./react/public/index.html:/react/public/index.html
      - ./react/src:/react/src/
