version: '3.7'
services:
  # React for the front
  react:
    build:
      context: ./react/
    ports:
      - "3000:3000"
    volumes:
      - ./react/public/:/react/public/
      - ./react/src:/react/src/
      # Exclude
      - exclusion:/react/public/js
  #Nginx for reverse proxy
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/front.conf:/etc/nginx/conf.d/front.conf:ro
  # flask(python) fot backend
  python:
    build:
      context: ./python/
    ports:
      - "5000:5000"
    volumes:
      - ./python/scripts/:/code/:ro
    restart: always
  # MySQL
  db:
    build:
      context: ./db/
    ports:
      - "3306:3306"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./db/sql:/
  # Redis
  redis:
    image: "redis:alpine"

volumes:
  exclusion:
    driver: 'local'
