version: '3.7'
services:
  # React
  react:
    build:
      context: ./react/
    ports:
      - "3000:3000"
    volumes:
      - ./react/public/:/react/public/
      - ./react/src:/react/src/
      # Exclude
      - exclusion:/react/public/js

volumes:
  exclusion:
    driver: 'local'
